name: "Main Branch Protection"
target: "branch"
enforcement: "active"

conditions:
  ref_name:
    include: 
      - "~DEFAULT_BRANCH"
    exclude: []

rules:
  - type: "pull_request"
    parameters:
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: false
      require_last_push_approval: false
      required_approving_review_count: 1
      required_review_thread_resolution: true

  - type: "required_status_checks"
    parameters:
      strict_required_status_checks_policy: true
      required_status_checks:
        - context: "Code Linting"
          integration_id: 15368
        - context: "Tests"
          integration_id: 15368
        - context: "Security Scan"
          integration_id: 15368

  - type: "non_fast_forward"
    parameters: {}

  - type: "required_signatures"
    parameters: {}

  - type: "deletion"
    parameters: {}

  - type: "force_push"
    parameters: {}

bypass_actors:
  - actor_id: 1
    actor_type: "OrganizationAdmin"
    bypass_mode: "always"